language: php

php:
  - 5.6
  - 7.0
  - hhvm
  - nightly
  
cache:
  directories:
    - $HOME/.composer/cache

build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=clover.file'
                coverage:
                    file: 'clover.file'
                    format: 'php-clover'

before_install:
  - composer self-update
  - composer validate
  - composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
