language: php

php:
  - 5.6
  - 7.0
  - hhvm
  - nightly
  
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer validate
  - composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit

